### ISSUE TITLE
option to ignore download paths

### ISSUE THREAD

**Issue by bernhardreiter** [csaf-poc/csaf_distribution#140]
A user wants to configure advisory paths that are ignored to for downloading, checking and aggregating.

Two motivations:
 1. Avoid error messages for paths that are advertised, but not accessible, e.g. TLP:AMBER where I do not have access.
 2. Ignore advisories I do not want.

Especially if the downloading is repeated, like an everyday run of the aggregator, the error message are unhelpful. It is similiar if the checker or the downloader are run as part of a repeating process.

**Comment by bernhardreiter** [comment]
### technical considerations
It may make sense to allow specifying a pattern or several patterns somehow.

**Comment by JanHoefelmeyer** [comment]
These options need to be configurable via a config file and as command line parameters.

**Comment by JanHoefelmeyer** [comment]
The currently open PRs implement the following functionalities:

Via a TOML file or via command line parameters, a slice of Regular Expressions can be given unto the ignorepattern option, which will cause the tool to ignore all files whose path contain any of these patterns. 

https://github.com/csaf-poc/csaf_distribution/pull/419 ( Downloader: ignore advisories by given patterns #419 ) implements this for the csaf_downloader

https://github.com/csaf-poc/csaf_distribution/pull/420 ( Checker: ignore advisories by given patterns #420 ) implements this for the csaf_checker

https://github.com/csaf-poc/csaf_distribution/pull/421 ( Downloader: ignore advisories by given patterns #421 ) implements this for the csaf_aggregator

Due to the nature of these checks, entire directories as well as singular files can be excluded from all three tools. This should solve the issue.

**Comment by s-l-teichmann** [comment]
This is resolved by #419 #420 and #421
