### ISSUE TITLE
Required field "update_interval" in aggregator.json missing

### ISSUE THREAD

**Issue by mfd2007** [csaf-poc/csaf_distribution#276]
CSAF-Standard define the field "update_interval" for every publisher that a aggregator mirrors. https://github.com/oasis-tcs/csaf/blob/ba8639f0602ac2cb76b7b8435790615a43987ba4/csaf_2.0/prose/csaf-v2-editor-draft.md?plain=1#L6228

Specification in aggregator.json-schema:
https://github.com/oasis-tcs/csaf/blob/ba8639f0602ac2cb76b7b8435790615a43987ba4/csaf_2.0/json_schema/aggregator_json_schema.json#L176-L180

https://github.com/oasis-tcs/csaf/blob/ba8639f0602ac2cb76b7b8435790615a43987ba4/csaf_2.0/json_schema/aggregator_json_schema.json#L192-L204

This can be achieved with an additional config field for every publisher in the aggregator.toml.

**Comment by tschmidtb51** [comment]
This is a mandatory field for CSAF publisher entries (see: https://github.com/oasis-tcs/csaf/blob/ba8639f0602ac2cb76b7b8435790615a43987ba4/csaf_2.0/json_schema/aggregator_json_schema.json#L179).

**Comment by s-l-teichmann** [comment]
I will have a look at it. If I see i correctly the whole `csaf_publishers` list is
currently not generated in the `aggregator.json`

**Comment by s-l-teichmann** [comment]
PR #278 should address this.

If a provider's domain starts with `https://` its considered a publisher.
These publishers are now added to the `csaf_publishers` list instead of
the `csaf_providers` list which was used before.

The mandatory value of `update_interval` can be configured for
each publisher (provider) individually. If not given it falls back
to the global `update_interval`. If this is not given either the
default is `on best effort`.
