### ISSUE TITLE
Add a check for requirement 2

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-poc/csaf_distribution#302]
We should add a check for [requirement 2](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html#712-requirement-2-filename) to the `csaf_checker`.

This might also be a question for the other programs...

**Comment by bernhardreiter** [comment]
The downloader shall reject non-compliant filenames.

**Comment by s-l-teichmann** [comment]
PR #330 adds this to the checker.

State of the other tools:
* The uploader checks the schema optionally. This is okay IMHO because:
* The validator checks the schema and the remote validator if configured.
* The provider checks the the schema and uses the remote validator if configured.
* The downloader checks the schema and the remote validator if configured,
* The aggregator checks the schema and the remote validator if configured.
