### ISSUE TITLE
Document config options for CSAF provider

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-poc/csaf_distribution#32]
The CSAF provider comes with many options. They should be documented (including their default value) and explained.

**Comment by tschmidtb51** [comment]
https://github.com/csaf-poc/csaf_distribution/blob/44cd02bdc2b953bc825f6d0c674dcd07005fc687/cmd/csaf_provider/config.go#L152
```suggestion
 Name:      func(s string) *string { return &s }("Example"),
```

**Comment by tschmidtb51** [comment]
@bernhardreiter I just had to re-open that as it was not completed.

**Comment by bernhardreiter** [comment]
@tschmidtb51 merged, because it seems to fit your suggested use better. (We had asked back on the "ACME" example, see https://github.com/csaf-poc/csaf_distribution/pull/40#discussion_r803847888, this is why I've thought we were already good enough here.) Thanks for doing your suggestion directly as pullrequest.
