### ISSUE TITLE
Shall a lockfile be used by default in the aggregator

### ISSUE THREAD

**Issue by bernhardreiter** [csaf-poc/csaf_distribution#344]
Current default in the aggregator is to not use a lockfile. 
It means that two instances with the same configuration can be started any may interfere with each other.
This could happen if one interim scan takes too long and the next is already started.
Is this the right default?

**Comment by tschmidtb51** [comment]
> Is this the right default?

Potentially not. I'm open to that change.

**Comment by bernhardreiter** [comment]
We want to change the default to using a lock file. 

* Shall be pointed out in the release notes.
* okay with 2.2.0 version number
* Can be switched off by explicit configuration.

**Comment by JanHoefelmeyer** [comment]
If a lock file is configured but the option to not use a lock file is also set to true, how do we want to handle this?

 * Use configured lock file and have the switch only be effective if no lock file was given?
 * Use no lock file, neither the default one nor the explicitely configured one?
 * Throw an error because having both configured points to a faulty config?

**Comment by tschmidtb51** [comment]
IMHO following the principle of least astonishment, I would expect the 2 option ("I said 'no lock file' so it is no lock file even if I told you where to put it if I would have wanted one.")

**Comment by s-l-teichmann** [comment]
Having an extra flag `no_lock` to say that the otherwise configured 'lock-file` should be ignored seem a bit unfortunate and contradictory. Why not the following:

* If no explicit `lock-file` use the default.
* If `lock-file` is the empty string don't use the lock file.
* If `lock-file` is not empty use this as the path.

**Comment by tschmidtb51** [comment]
@s-l-teichmann I guess my answer lead into that direction. I'm happy with both approaches. So - I would suggest that @s-l-teichmann decides which one should be implemented (as you are closer to the code and @JanHoefelmeyer).

**Comment by tschmidtb51** [comment]
@JanHoefelmeyer Please consult with @s-l-teichmann and update #351 if necessary. Please also document the decision (either back in draft mode or an explicit "@tschmidtb51 ready for review")  so that I know whether I should review #351 or whether you are working on that again.

Thanks!
