### ISSUE TITLE
Create unique user-agent

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-poc/csaf_distribution#500]
Currently, we use the standard go-http-lib user agent. However, to be able to better track the usage of the tool, we should use our own user-agent string, e.g., `"<program> <version>"`.

**Comment by bernhardreiter** [comment]
As shown in https://github.com/csaf-poc/csaf_distribution/issues/500 it is possible to set an individual user-agent with `--header User-Agent:curl/7.55.1` so this issue is about the default user agent. And the implementation should keep the ability to override the default user-agent.

@tschmidtb51 as you have marked this as _important_ do you want it done as _service+dev_?
(If so, it is okay to add the label.)
